"""Illustrative district-level datasets for three real Indian districts.

These figures are modeled on the general character of each district's
economy (commodity mixes, agricultural calendar, market density) - they are
NOT live Agmarknet/Udyam pulls. Every number here is static and auditable;
none of it is generated by the LLM. The voice agent and advisory layer read
FROM this data, never invent numbers of their own.
"""

from __future__ import annotations

CITY_DATA: dict[str, dict] = {
    "latur": {
        "label": "Latur, Maharashtra",
        "state": "Maharashtra",
        "district": "Latur",
        "blocks": ["Latur", "Ausa", "Nilanga", "Renapur", "Chakur"],
        "profile_note": "Major tur dal (pigeon pea) and soybean mandi belt in the Marathwada region.",
        "commodities": {
            "tur_dal": {"unit": "quintal", "low": 6200, "high": 8400, "current": 7600},
            "soybean": {"unit": "quintal", "low": 3800, "high": 4900, "current": 4500},
            "milk": {"unit": "litre", "low": 32, "high": 44, "current": 40},
            "cotton_cloth": {"unit": "metre", "low": 85, "high": 150, "current": 98},
            "grocery_basket": {"unit": "basket index", "low": 100, "high": 126, "current": 118},
        },
        "competition_density": {
            "vendor": 12, "dairy": 7, "tailoring": 5, "retail": 13, "handicrafts": 4, "food_stall": 10,
        },
        "seasonal_peak": {
            "vendor": "Rabi harvest arrival (Nov-Dec)",
            "dairy": "Diwali sweets season (Oct)",
            "tailoring": "Wedding season (Nov-Feb)",
            "retail": "Diwali retail rush (Oct)",
            "handicrafts": "Diwali gifting season (Oct)",
            "food_stall": "Local yatra/jatra season (Jan-Feb)",
        },
    },
    "sitapur": {
        "label": "Sitapur, Uttar Pradesh",
        "state": "Uttar Pradesh",
        "district": "Sitapur",
        "blocks": ["Biswan", "Mahmoodabad", "Sidhauli", "Laharpur", "Machhrehta"],
        "profile_note": "Sugarcane and paddy belt in central Awadh, dense weekly haats (rural markets).",
        "commodities": {
            "tomato": {"unit": "kg", "low": 12, "high": 38, "current": 31},
            "sugarcane": {"unit": "quintal", "low": 340, "high": 380, "current": 355},
            "milk": {"unit": "litre", "low": 38, "high": 52, "current": 48},
            "cotton_cloth": {"unit": "metre", "low": 90, "high": 160, "current": 102},
            "wheat_flour": {"unit": "kg", "low": 26, "high": 40, "current": 29},
        },
        "competition_density": {
            "vendor": 14, "dairy": 6, "tailoring": 4, "retail": 11, "handicrafts": 3, "food_stall": 9,
        },
        "seasonal_peak": {
            "vendor": "Diwali produce demand (Oct)",
            "dairy": "Diwali sweets season (Oct)",
            "tailoring": "Wedding & festival season (Oct-Nov)",
            "retail": "Diwali retail rush (Oct)",
            "handicrafts": "Diwali gifting season (Oct)",
            "food_stall": "Diwali-Chhath snacking season (Oct-Nov)",
        },
    },
    "indore": {
        "label": "Indore, Madhya Pradesh",
        "state": "Madhya Pradesh",
        "district": "Indore",
        "blocks": ["Sanwer", "Depalpur", "Mhow", "Hatod", "Rau"],
        "profile_note": "MP's largest commercial hub - dense retail, textile and namkeen (snack) trade.",
        "commodities": {
            "soybean": {"unit": "quintal", "low": 3900, "high": 5000, "current": 4600},
            "milk": {"unit": "litre", "low": 40, "high": 54, "current": 50},
            "cotton_cloth": {"unit": "metre", "low": 95, "high": 175, "current": 120},
            "grocery_basket": {"unit": "basket index", "low": 102, "high": 130, "current": 124},
            "wheat_flour": {"unit": "kg", "low": 27, "high": 41, "current": 31},
        },
        "competition_density": {
            "vendor": 16, "dairy": 9, "tailoring": 8, "retail": 18, "handicrafts": 5, "food_stall": 15,
        },
        "seasonal_peak": {
            "vendor": "Navratri-Diwali produce demand (Oct)",
            "dairy": "Diwali sweets season (Oct)",
            "tailoring": "Wedding & festival season (Oct-Feb)",
            "retail": "Diwali retail rush (Oct)",
            "handicrafts": "Diwali gifting season (Oct)",
            "food_stall": "Navratri snacking season (Sep-Oct)",
        },
    },
}

COMPETITION_DENSITY_MAX = 20

VIABILITY_WEIGHTS = {
    "vendor": {"price": 0.45, "competition": 0.2, "season": 0.35},
    "dairy": {"price": 0.35, "competition": 0.25, "season": 0.4},
    "tailoring": {"price": 0.2, "competition": 0.5, "season": 0.3},
    "retail": {"price": 0.3, "competition": 0.4, "season": 0.3},
    "handicrafts": {"price": 0.25, "competition": 0.35, "season": 0.4},
    "food_stall": {"price": 0.3, "competition": 0.3, "season": 0.4},
}

BUSINESS_TYPES = [
    {"value": "vendor", "label": "Vegetable / Fruit Vendor"},
    {"value": "dairy", "label": "Dairy (Milk & Products)"},
    {"value": "tailoring", "label": "Tailoring & Stitching"},
    {"value": "retail", "label": "Retail / Kirana Shop"},
    {"value": "handicrafts", "label": "Handicrafts"},
    {"value": "food_stall", "label": "Food Stall / Snacks"},
]

# Which commodity from each district's basket represents each business type.
BUSINESS_COMMODITY_MAP = {
    "vendor": ["tomato", "soybean", "tur_dal"],
    "dairy": ["milk"],
    "tailoring": ["cotton_cloth"],
    "retail": ["grocery_basket", "wheat_flour"],
    "handicrafts": ["cotton_cloth", "grocery_basket"],
    "food_stall": ["wheat_flour", "grocery_basket"],
}


def pick_commodity(district_key: str, business_type: str) -> tuple[str, dict] | None:
    """Pick the first commodity available in this district for a business type."""
    district = CITY_DATA.get(district_key)
    if not district:
        return None
    for commodity_key in BUSINESS_COMMODITY_MAP.get(business_type, []):
        if commodity_key in district["commodities"]:
            return commodity_key, district["commodities"][commodity_key]
    return None
